#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/write-env.sh [--force] [--dry-run]

Create or update .env with machine-local paths detected from this checkout and
the local Hermes installation. Existing values are preserved by default; missing
keys are appended.

Options:
  --force     Rewrite .env completely from detected defaults.
  --dry-run   Print what would change without writing.
  -h, --help  Show this help.
USAGE
}

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
FORCE=0
DRY_RUN=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force)
      FORCE=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

detect_hermes_home() {
  if [[ -n "${HERMES_HOME:-}" ]]; then
    printf '%s\n' "$HERMES_HOME"
    return
  fi

  if [[ -d "$HOME/.hermes" ]]; then
    printf '%s\n' "$HOME/.hermes"
    return
  fi

  # Official Hermes installs use ~/.hermes as the default home. If Hermes is
  # installed but HERMES_HOME is not set yet, this is still the path Hermes will
  # create/use by default.
  printf '%s\n' "$HOME/.hermes"
}

detected_hermes_home="$(detect_hermes_home)"
detected_memory_root="${HERMES_MEMORY_ROOT:-$REPO_ROOT/memory}"

default_env_content() {
  cat <<EOF
# Machine-local config generated by scripts/write-env.sh.
# Do not commit this file.

HERMES_CONTEXT_REPO=$REPO_ROOT
HERMES_MEMORY_ROOT=$detected_memory_root
HERMES_HOME=$detected_hermes_home

# Account labels only. Put real OAuth/client credentials in your Hermes integration UI, local mail client config, or secret manager.
PERSONAL_EMAIL_ACCOUNTS=personal_primary:personal@example.com,personal_projects:projects@example.com
WORK_EMAIL_ACCOUNT=you@company.com

# Ticket provider labels only.
WORK_TICKET_PROVIDER=linear
WORK_TICKET_WORKSPACE=your-workspace

# Discord gateway token. Leave blank until you create the bot locally.
DISCORD_HERMES_BOT_TOKEN=
EOF
}

write_file() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "DRY RUN: would write $ENV_FILE with detected local paths."
    default_env_content
    return
  fi

  default_env_content > "$ENV_FILE"
  echo "Wrote $ENV_FILE with detected local paths."
}

replace_key_value() {
  local key="$1"
  local value="$2"

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "DRY RUN: would replace placeholder value for $key in $ENV_FILE"
    return
  fi

  local escaped_value
  escaped_value="$(printf '%s' "$value" | sed 's/[&/\\]/\\&/g')"
  sed -i.bak "s/^${key}=.*/${key}=${escaped_value}/" "$ENV_FILE"
  rm -f "$ENV_FILE.bak"
  echo "Updated placeholder value for .env key: $key"
}

set_or_preserve_key() {
  local key="$1"
  local value="$2"
  shift 2
  local placeholders=("$@")

  if grep -qE "^${key}=" "$ENV_FILE" 2>/dev/null; then
    local current_value
    current_value="$(grep -E "^${key}=" "$ENV_FILE" | tail -n 1 | cut -d= -f2-)"

    for placeholder in "${placeholders[@]}"; do
      if [[ "$current_value" == "$placeholder" ]]; then
        replace_key_value "$key" "$value"
        return
      fi
    done

    return
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "DRY RUN: would append missing key $key to $ENV_FILE"
    return
  fi

  printf '\n%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  echo "Added missing key to .env: $key"
}

if [[ ! -f "$ENV_FILE" || "$FORCE" -eq 1 ]]; then
  write_file
  exit 0
fi

set_or_preserve_key HERMES_CONTEXT_REPO "$REPO_ROOT" \
  "/absolute/path/to/multi-level-hermes"
set_or_preserve_key HERMES_MEMORY_ROOT "$detected_memory_root" \
  "/absolute/path/to/multi-level-hermes/memory"
set_or_preserve_key HERMES_HOME "$detected_hermes_home" \
  "/home/you/.hermes" \
  "~/.hermes" \
  ""
set_or_preserve_key PERSONAL_EMAIL_ACCOUNTS "personal_primary:personal@example.com,personal_projects:projects@example.com"
set_or_preserve_key WORK_EMAIL_ACCOUNT "you@company.com"
set_or_preserve_key WORK_TICKET_PROVIDER "linear"
set_or_preserve_key WORK_TICKET_WORKSPACE "your-workspace"
set_or_preserve_key DISCORD_HERMES_BOT_TOKEN ""

echo ".env already exists; preserved real values, replaced known path placeholders, and added any missing keys."
